### ISSUE TITLE
undefined method `dump_schemas'

### ISSUE THREAD

**Issue by alagram** [GUI/rails_425_structure_dump_patch#1]
Thanks for this solution. 

I'm running  ruby version `ruby 2.1.2p95 (2014-05-08 revision 45877)` rails version `Rails 4.2.5.1`. Just installed your gem by following the instructions and keep getting this:

```
rake aborted!
NoMethodError: undefined method `dump_schemas' for ActiveRecord::Base:Class
-e:1:in `<main>'
Tasks: TOP => db:structure:dump
(See full trace by running task with --trace)
```

Have you came across this? Thanks so much for your help.

**Comment by jmcnevin** [comment]
Seeing the same error here.

**Comment by brega** [comment]
`ActiveRecord::Base.dump_schemas` was introduced by [7ab36f4](https://github.com/GUI/rails/commit/7ab36f4532c891e8a4bdaee8924a197311ff25ffl)

Undoing parts of it helps gets past this issue.

**Comment by GUI** [comment]
Whoops, sorry about the problem and for the issue slipping past me.

I'm not sure if it's relevant now that Rails 4.2.6 is out, but this should be fixed in master (by https://github.com/GUI/rails_425_structure_dump_patch/commit/ab71a366f4c26904bb8f9b8c3602638222db317a). I had inadvertently used the `dump_schemas` method, which is a Rails 5 feature that I had also back ported with the [activerecord-postgres-dump-schemas](https://github.com/GUI/activerecord-postgres-dump-schemas) gem. So if you happened to have that gem installed, it worked, but otherwise, it was broken.
